# Generated by Django 3.2.3 on 2021-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_path', models.URLField()),
                ('short_path', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
